
// This file was auto-generated by ML.NET Model Builder. 

using MLModel_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLModel.ModelInput sampleData = new MLModel.ModelInput()
{
    MaHD = 10248F,
    MaHH = 1042F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual SoLuong with predicted SoLuong from sample data...\n\n");


Console.WriteLine($"MaHD: {10248F}");
Console.WriteLine($"MaHH: {1042F}");
Console.WriteLine($"SoLuong: {10F}");


// Make a single prediction on the sample data and print results
var predictionResult = MLModel.Predict(sampleData);
Console.WriteLine($"\n\nPredicted SoLuong: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

